/**
 * AUTO-GENERATED FILE - DO NOT EDIT.
 *
 * This file is generated by the API Service (Swagger -> mainApiEndpoints).
 * To regenerate, run (from api/): `npm run sync:libs-endpoints`
 *
 * Notes:
 * - Types in JSDoc are derived from Swagger schemas, then mapped from *Dto -> interface
 *   using `implements I...` declarations in the API source.
 */

/**
 * Auth Endpoints
 */
export const authEndpoints = {
  /**
   * Change Password application
   * @param data: IAuthChangePassword
   * @returns boolean
   */
  changePassword: {
    method: 'POST',
    path: '/auth/change-password',
  },
  /**
   * Confirm Register application
   * @param data: IAuthConfirmRegister
   * @returns IAuthResponse
   */
  confirmRegister: {
    method: 'POST',
    path: '/auth/confirm-register',
  },
  /**
   * Confirm Register application with code
   * @param data: IAuthConfirmRegisterCode
   * @returns IAuthResponse
   */
  confirmRegisterCode: {
    method: 'POST',
    path: '/auth/confirm-register-code',
  },
  /**
   * Forgot Password application
   * @param data: IAuthForgotPassword
   * @returns boolean
   */
  forgotPassword: {
    method: 'POST',
    path: '/auth/forgot-password',
  },
  /**
   * Get Me
   * @returns IUser
   */
  getMe: {
    method: 'GET',
    path: '/auth/me',
  },
  /**
   * Log In application
   * @param data: IAuthLogin
   * @returns IAuthResponse
   */
  login: {
    method: 'POST',
    path: '/auth/login',
  },
  /**
   * [Permissions: USER_MANAGE] - Log In application
   * @param data: IEmailRequire
   * @returns IAuthResponse
   */
  loginByAdmin: {
    method: 'POST',
    path: '/auth/login-by-admin',
  },
  /**
   * Log Out application
   * @returns boolean
   */
  logout: {
    method: 'POST',
    path: '/auth/logout',
  },
  /**
   * Refresh Token application
   * @param data: IAuthRefreshToken
   * @returns IAuthResponse
   */
  refreshToken: {
    method: 'POST',
    path: '/auth/refresh-token',
  },
  /**
   * Register application
   * @param data: IAuthRegister
   * @returns IAuthResponse
   */
  register: {
    method: 'POST',
    path: '/auth/register',
  },
  /**
   * Resend Register application
   * @param data: IAuthSendRegister
   * @returns boolean
   */
  resendRegister: {
    method: 'POST',
    path: '/auth/resend-register',
  },
  /**
   * Reset Password application
   * @param data: IAuthResetPassword
   * @returns boolean
   */
  resetPassword: {
    method: 'POST',
    path: '/auth/reset-password',
  },
} as const;

/**
 * Email Endpoints
 */
export const emailEndpoints = {
  /**
   * [Permissions: GLOBAL] - [Permissions: GLOBAL] - Send email
   * @param data: IEmailSendMulti
   * @returns boolean
   */
  sendEmail: {
    method: 'POST',
    path: '/email',
  },
} as const;

/**
 * Email Template Endpoints
 */
export const emailTemplateEndpoints = {
  /**
   * [Permissions: GLOBAL] - Get all email template
   * @param query: IEmailTemplateFindMany
   * @returns IFindManyResponse<'emailTemplates', IEmailTemplate>
   */
  findMany: {
    method: 'GET',
    path: '/email-template',
  },
  /**
   * [Permissions: GLOBAL] - Get email template by id
   * @param params: { id: string }
   * @returns IEmailTemplate
   */
  findOne: {
    method: 'GET',
    path: '/email-template/{id}',
  },
  /**
   * [Permissions: GLOBAL] - Get email template by key
   * @param params: { key: string }
   * @returns IEmailTemplate
   */
  findOneByKey: {
    method: 'GET',
    path: '/email-template/by-key/{key}',
  },
  /**
   * [Permissions: GLOBAL] - Update email template
   * @param data: IEmailTemplateUpdate
   * @param params: { id: string }
   * @returns IEmailTemplate
   */
  update: {
    method: 'PUT',
    path: '/email-template/{id}',
  },
} as const;

/**
 * General Endpoints
 */
export const generalEndpoints = {
  /**
   * Get site info
   * @returns ISiteInfo
   */
  getSiteInfo: {
    method: 'GET',
    path: '/general/site-info',
  },
  /**
   * Seed data
   * @param query: ISeedData
   */
  seedData: {
    method: 'POST',
    path: '/general/seed-data',
  },
  /**
   * Get status
   * @returns any
   */
  status: {
    method: 'GET',
    path: '/general/status',
  },
  /**
   * [Permissions: GLOBAL] - Update site info
   * @param data: ISiteInfo
   * @returns any
   */
  updateSiteInfo: {
    method: 'POST',
    path: '/general/site-info',
  },
} as const;

/**
 * Health Endpoints
 */
export const healthEndpoints = {
  /**
   * Health check
   */
  health: {
    method: 'GET',
    path: '/health',
  },
} as const;

/**
 * Media Endpoints
 */
export const mediaEndpoints = {
  /**
   * Delete Image.
   * @param params: { id: string }
   * @returns IMedia
   */
  delete: {
    method: 'DELETE',
    path: '/media/{id}',
  },
  /**
   * Delete many media.
   * @param data: { ids: string[] }
   * @returns IMedia[]
   */
  deleteMany: {
    method: 'DELETE',
    path: '/media/delete-many',
  },
  /**
   * Find many
   * @param query: IMediaFindMany
   * @returns IFindManyResponse<'medias', IMedia>
   */
  findMany: {
    method: 'GET',
    path: '/media',
  },
  /**
   * Find one by id
   * @param params: { id: string }
   * @returns IMedia
   */
  findOneById: {
    method: 'GET',
    path: '/media/{id}',
  },
  /**
   * [Permissions: GLOBAL]
   * @returns IMedia[]
   */
  removeMediaNotUsed: {
    method: 'POST',
    path: '/media/remove-not-used',
  },
  /**
   * Save info unsplash
   * @param data: IMediaSaveRemote
   * @returns any
   */
  saveInfoUnsplash: {
    method: 'POST',
    path: '/media/save-remote',
  },
  /**
   * [Permissions: MEDIA_UPDATE]
   * @param data: IMediaUpdate
   * @param params: { id: string }
   * @returns any
   */
  update: {
    method: 'PUT',
    path: '/media/{id}',
  },
  /**
   * Upload media.
   * @param query: IMediaUpload
   * @returns IMedia
   */
  upload: {
    method: 'POST',
    path: '/media',
  },
  /**
   * Upload media by url.
   * @param query: IMediaUploadFromUrl
   * @returns any
   */
  uploadFromUrl: {
    method: 'POST',
    path: '/media/url',
  },
} as const;

/**
 * Notification Endpoints
 */
export const notificationEndpoints = {
  /**
   * get all notification
   * @param query: INotificationFindMany
   * @returns IFindManyResponse<'notifications', INotification>
   */
  findMany: {
    method: 'GET',
    path: '/notification',
  },
  /**
   * get notification system
   * @returns INotificationSystem
   */
  getSystems: {
    method: 'GET',
    path: '/notification/system',
  },
  /**
   * mark notification as read
   * @param params: { id: string }
   * @returns boolean
   */
  read: {
    method: 'POST',
    path: '/notification/read/{id}',
  },
  /**
   * mark all notification as read
   * @returns boolean
   */
  readAll: {
    method: 'POST',
    path: '/notification/read/all',
  },
  /**
   * get notification stats
   * @returns INotificationStats
   */
  stats: {
    method: 'GET',
    path: '/notification/stats',
  },
} as const;

/**
 * Payment Endpoints
 */
export const paymentEndpoints = {
  /**
   * [Permissions: PAYMENT_APPROVE] - Approve payment
   * @param query: { affiliateSessionId: string }
   * @param params: { id: string }
   * @returns IPayment
   */
  approve: {
    method: 'POST',
    path: '/payment/approve/{id}',
  },
  /**
   * Cancel payment
   * @param params: { id: string }
   * @returns IPayment
   */
  cancel: {
    method: 'POST',
    path: '/payment/cancel/{id}',
  },
  /**
   * Create payment
   * @param data: PaymentCreateDto
   * @param query: { affiliateSessionId: string }
   * @returns IPayment
   */
  create: {
    method: 'POST',
    path: '/payment',
  },
  /**
   * Find many payments
   * @param query: IPaymentFindMany
   * @returns IFindManyResponse<'payments', IPayment>
   */
  findMany: {
    method: 'GET',
    path: '/payment',
  },
  /**
   * Get payment with id
   * @param params: { id: string }
   * @returns IPayment
   */
  findOne: {
    method: 'GET',
    path: '/payment/{id}',
  },
  /**
   * Get Payment Summary
   * @param query: IPaymentFindMany
   * @returns IPaymentSummary
   */
  getSummary: {
    method: 'GET',
    path: '/payment/summary',
  },
  /**
   * [Permissions: PAYMENT_REJECT] - Reject payment
   * @param data: string
   * @param params: { id: string }
   * @returns IPayment
   */
  reject: {
    method: 'POST',
    path: '/payment/reject/{id}',
  },
  /**
   * [Permissions: PAYMENT_REOPEN] - Reopen payment
   * @param data: string
   * @param params: { id: string }
   * @returns IPayment
   */
  reopen: {
    method: 'POST',
    path: '/payment/reopen/{id}',
  },
  /**
   * Update payment
   * @param data: IPaymentUpdate
   * @param params: { id: string }
   * @returns IPayment
   */
  update: {
    method: 'PUT',
    path: '/payment/{id}',
  },
} as const;

/**
 * Post Endpoints
 */
export const postEndpoints = {
  /**
   * Count Post
   * @param query: IPostFindMany
   * @returns number
   */
  countPost: {
    method: 'GET',
    path: '/post/count',
  },
  /**
   * Create post
   * @param data: IPostCreate
   * @returns IPost
   */
  create: {
    method: 'POST',
    path: '/post',
  },
  /**
   * Delete post
   * @param params: { id: string }
   * @returns IPost
   */
  delete: {
    method: 'DELETE',
    path: '/post/{id}',
  },
  /**
   * Find Many Post
   * @param query: IPostFindMany
   * @returns IFindManyResponse<'posts', IPost>
   */
  findMany: {
    method: 'GET',
    path: '/post',
  },
  /**
   * Get post revisions
   * @param query: IPostRevisionFindMany
   * @param params: { id: string }
   */
  findManyRevisions: {
    method: 'GET',
    path: '/post/{id}/revisions',
  },
  /**
   * Find one Post
   * @param params: { id: string }
   * @returns IPost
   */
  findOneById: {
    method: 'GET',
    path: '/post/{id}',
  },
  /**
   * Get post by slug
   * @param params: { slug: string }
   * @returns IPost
   */
  findOneBySlug: {
    method: 'GET',
    path: '/post/slug/{slug}',
  },
  /**
   * Get post by slug
   * @param params: { slug: string }
   * @returns IPost
   */
  findOneBySlugWithDomain: {
    method: 'GET',
    path: '/post/slug/{slug}/domain',
  },
  /**
   * Get post bounty
   * @param params: { id: string }
   * @returns IPostBounty[]
   */
  getBounty: {
    method: 'GET',
    path: '/post/{id}/bounty',
  },
  /**
   * Get Post Summary
   * @returns IPostSummary
   */
  getPostSummary: {
    method: 'GET',
    path: '/post/summary',
  },
  /**
   * Get revision detail
   * @param params: { id: string }
   */
  getRevisionDetail: {
    method: 'POST',
    path: '/post/{id}/revisions',
  },
  /**
   * Get Sitemap
   * @param query: ITakeSkip
   * @returns IPost[]
   */
  sitemap: {
    method: 'GET',
    path: '/post/sitemap',
  },
  /**
   * Get Sitemap count
   * @returns number
   */
  sitemapCount: {
    method: 'GET',
    path: '/post/sitemap/count',
  },
  /**
   * Get trending post
   * @param query: IPostFindMany
   * @returns IPost[]
   */
  trendingPosts: {
    method: 'GET',
    path: '/post/trending',
  },
  /**
   * Update post by id
   * @param data: IPostUpdate
   * @param params: { id: string }
   * @returns IPost
   */
  update: {
    method: 'PUT',
    path: '/post/{id}',
  },
  /**
   * Update statistic
   * @param params: { id: string }
   * @returns boolean
   */
  updateStatistic: {
    method: 'POST',
    path: '/post/{id}/statistic',
  },
  /**
   * Create/update post bounty
   * @param data: IPostBountyCreate
   * @param params: { id: string }
   * @returns boolean
   */
  upsertBounty: {
    method: 'POST',
    path: '/post/{id}/bounty',
  },
} as const;

/**
 * Root Endpoints
 */
export const rootEndpoints = {
  /**
   * Root
   */
  root: {
    method: 'GET',
    path: '/',
  },
} as const;

/**
 * User Endpoints
 */
export const userEndpoints = {
  /**
   * Add media to gallery
   * @param params: { mediaId: string }
   * @returns boolean
   */
  addGalleryMedia: {
    method: 'POST',
    path: '/user/gallery/{mediaId}',
  },
  /**
   * Get users count
   * @param query: IUserFindMany
   * @returns number
   */
  countUsers: {
    method: 'GET',
    path: '/user/count',
  },
  /**
   * [Permissions: USER_CREATE] - Create user
   * @param data: IUserCreate
   * @returns IUser
   */
  create: {
    method: 'POST',
    path: '/user',
  },
  /**
   * Delete user
   * @param params: { id: string }
   * @returns IUser
   */
  delete: {
    method: 'DELETE',
    path: '/user/{id}',
  },
  /**
   * Delete many user.
   * @param data: { ids: string[] }
   * @returns IUser[]
   */
  deleteMany: {
    method: 'DELETE',
    path: '/user/delete-many',
  },
  /**
   * Get user followers
   * @param query: IUserFindMany
   * @param params: { id: string }
   * @returns IFindManyResponse<'users', IUser>
   */
  findFollowers: {
    method: 'GET',
    path: '/user/{id}/followers',
  },
  /**
   * Get user followings
   * @param query: IUserFindMany
   * @param params: { id: string }
   * @returns IFindManyResponse<'users', IUser>
   */
  findFollowings: {
    method: 'GET',
    path: '/user/{id}/followings',
  },
  /**
   * Get user gallery
   * @param query: IFindMany
   * @param params: { id: string }
   * @returns IFindManyResponse<'medias', IMedia>
   */
  findGallery: {
    method: 'GET',
    path: '/user/{id}/gallery',
  },
  /**
   * [Permissions: USER_VIEW] - Get all users
   * @param query: IUserFindMany
   * @returns IFindManyResponse<'users', IUser>
   */
  findMany: {
    method: 'GET',
    path: '/user',
  },
  /**
   * Get user members
   * @param query: IUserFindMany
   * @param params: { id: string }
   * @returns IFindManyResponse<'users', IUser>
   */
  findMembers: {
    method: 'GET',
    path: '/user/{id}/members',
  },
  /**
   * [Permissions: USER_VIEW] - Get user by id
   * @param params: { id: string }
   * @returns IFindManyResponse<'users', IUser>
   */
  findOne: {
    method: 'GET',
    path: '/user/{id}',
  },
  /**
   * [Permissions: USER_VIEW] - Get User by username
   * @param params: { username: string }
   * @returns IUser
   */
  findOneByUsername: {
    method: 'GET',
    path: '/user/username/{username}',
  },
  /**
   * Get user stats
   * @param params: { id: string }
   * @returns IUserStats
   */
  findStats: {
    method: 'GET',
    path: '/user/{id}/stats',
  },
  /**
   * Follow user
   * @param params: { id: string }
   * @returns IUser
   */
  followUser: {
    method: 'POST',
    path: '/user/{id}/follow',
  },
  /**
   * Get follow status
   * @param params: { id: string }
   * @returns boolean
   */
  getFollowStatus: {
    method: 'GET',
    path: '/user/{id}/follow',
  },
  /**
   * Remove media from gallery
   * @param params: { mediaId: string }
   * @returns boolean
   */
  removeGalleryMedia: {
    method: 'DELETE',
    path: '/user/gallery/{mediaId}',
  },
  /**
   * Unfollow user
   * @param params: { id: string }
   * @returns IUser
   */
  unfollowUser: {
    method: 'DELETE',
    path: '/user/{id}/follow',
  },
  /**
   * Update user
   * @param data: IUserUpdate
   * @param params: { id: string }
   * @returns IUser
   */
  update: {
    method: 'PUT',
    path: '/user/{id}',
  },
} as const;

/**
 * Websocket Endpoints
 */
export const websocketEndpoints = {
  /**
   * Get online users
   * @param query: IWebsocketOnlineUser
   * @returns string[]
   */
  getOnlineUsers: {
    method: 'GET',
    path: '/websocket/online-users',
  },
  /**
   * [Permissions: GLOBAL]
   * @param data: ISystemNotification
   * @returns string
   */
  sendSystemNotification: {
    method: 'POST',
    path: '/websocket/send-system-notification',
  },
} as const;

/**
 * Transaction Endpoints
 */
export const transactionEndpoints = {
  /**
   * [Permissions: TRANSACTION_UPDATE] - Approve transaction
   * @param params: { id: string }
   * @returns ITransaction
   */
  approve: {
    method: 'POST',
    path: '/transaction/approve/{id}',
  },
  /**
   * Convert credits to commission
   * @param data: ITransactionConvertCommission
   * @returns boolean
   */
  convert: {
    method: 'POST',
    path: '/transaction/convert',
  },
  /**
   * [Permissions: TRANSACTION_CREATE] - Create transaction
   * @param data: ITransactionCreate
   * @returns ITransaction
   */
  create: {
    method: 'POST',
    path: '/transaction',
  },
  /**
   * Find many transactions
   * @param query: ITransactionFindMany
   * @returns IFindManyResponse<'transactions', ITransaction>
   */
  findMany: {
    method: 'GET',
    path: '/transaction',
  },
  /**
   * Get transaction with id
   * @param params: { id: string }
   * @returns ITransaction
   */
  findOne: {
    method: 'GET',
    path: '/transaction/{id}',
  },
  /**
   * [Permissions: TRANSACTION_UPDATE] - Reject transaction
   * @param params: { id: string }
   * @returns ITransaction
   */
  reject: {
    method: 'POST',
    path: '/transaction/reject/{id}',
  },
  /**
   * [Permissions: TRANSACTION_UPDATE] - Update transaction
   * @param data: ITransactionUpdate
   * @param params: { id: string }
   * @returns ITransaction
   */
  update: {
    method: 'PATCH',
    path: '/transaction/{id}',
  },
} as const;

/**
 * Role Endpoints
 */
export const roleEndpoints = {
  /**
   * [Permissions: ROLE_MANAGE] - Add permission
   * @param data: IPermissionUpdate
   * @param params: { id: string }
   * @returns boolean
   */
  addPermission: {
    method: 'POST',
    path: '/role/{id}/add',
  },
  /**
   * [Permissions: ROLE_MANAGE, ROLE_CREATE] - Create role
   * @param data: IRoleCreate
   * @returns IRole
   */
  createRole: {
    method: 'POST',
    path: '/role',
  },
  /**
   * Delete Role
   * @param params: { id: string }
   * @returns IRole
   */
  delete: {
    method: 'DELETE',
    path: '/role/{id}',
  },
  /**
   * [Permissions: ROLE_MANAGE] - Find one role
   * @param params: { id: string }
   * @returns IRole
   */
  findOneById: {
    method: 'GET',
    path: '/role/{id}',
  },
  /**
   * [Permissions: ROLE_MANAGE] - Get all permissions
   * @returns any[]
   */
  getPermissions: {
    method: 'GET',
    path: '/role/permissions',
  },
  /**
   * [Permissions: ROLE_MANAGE] - Get all roles
   * @param query: IFilterTakeSkip
   * @returns IFindManyResponse<'roles', IRole>
   */
  getRoles: {
    method: 'GET',
    path: '/role',
  },
  /**
   * [Permissions: ROLE_MANAGE] - Remove permission
   * @param data: IPermissionUpdate
   * @param params: { id: string }
   * @returns boolean
   */
  removePermission: {
    method: 'POST',
    path: '/role/{id}/remove',
  },
  /**
   * [Permissions: ROLE_MANAGE] - Reload permission
   * @returns {
    length: number;
    status: boolean;
  }
   */
  syncPermissions: {
    method: 'POST',
    path: '/role/permissions',
  },
  /**
   * [Permissions: ROLE_MANAGE] - Update role
   * @param data: IRoleUpdate
   * @param params: { id: string }
   * @returns IUser
   */
  update: {
    method: 'PUT',
    path: '/role/{id}',
  },
} as const;

export const mainApiEndpoints = {
  auth: authEndpoints,
  email: emailEndpoints,
  emailTemplate: emailTemplateEndpoints,
  general: generalEndpoints,
  health: healthEndpoints,
  role: roleEndpoints,
  media: mediaEndpoints,
  notification: notificationEndpoints,
  payment: paymentEndpoints,
  post: postEndpoints,
  root: rootEndpoints,
  user: userEndpoints,
  websocket: websocketEndpoints,
  transaction: transactionEndpoints,
} as const;
