export const permissions = {
  SUPER_ADMIN: 'SUPER_ADMIN',

  // User
  USER_VIEW: 'USER_VIEW',
  USER_MANAGE: 'USER_MANAGE',
  USER_CREATE: 'USER_CREATE',
  USER_DELETE: 'USER_DELETE',
  USER_UPDATE: 'USER_UPDATE',

  // Media
  MEDIA_VIEW: 'MEDIA_VIEW',
  MEDIA_MANAGE: 'MEDIA_MANAGE',
  MEDIA_CREATE: 'MEDIA_CREATE',
  MEDIA_UPDATE: 'MEDIA_UPDATE',
  MEDIA_DELETE: 'MEDIA_DELETE',

  // Email Template
  EMAIL_TEMPLATE_VIEW: 'EMAIL_TEMPLATE_VIEW',
  EMAIL_TEMPLATE_MANAGE: 'EMAIL_TEMPLATE_MANAGE',
  EMAIL_TEMPLATE_CREATE: 'EMAIL_TEMPLATE_CREATE',
  EMAIL_TEMPLATE_DELETE: 'EMAIL_TEMPLATE_DELETE',
  EMAIL_TEMPLATE_UPDATE: 'EMAIL_TEMPLATE_UPDATE',

  // Post
  POST_VIEW: 'POST_VIEW',
  POST_MANAGE: 'POST_MANAGE',
  POST_CREATE: 'POST_CREATE',
  POST_DELETE: 'POST_DELETE',
  POST_UPDATE: 'POST_UPDATE',

  // Category
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_MANAGE: 'CATEGORY_MANAGE',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',

  // Payment
  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_MANAGE: 'PAYMENT_MANAGE',
  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_UPDATE: 'PAYMENT_UPDATE',
  PAYMENT_DELETE: 'PAYMENT_DELETE',
  PAYMENT_APPROVE: 'PAYMENT_APPROVE',
  PAYMENT_REJECT: 'PAYMENT_REJECT',
  PAYMENT_REOPEN: 'PAYMENT_REOPEN',

  // Transaction
  TRANSACTION_VIEW: 'TRANSACTION_VIEW',
  TRANSACTION_MANAGE: 'TRANSACTION_MANAGE',
  TRANSACTION_CREATE: 'TRANSACTION_CREATE',
  TRANSACTION_UPDATE: 'TRANSACTION_UPDATE',
  TRANSACTION_DELETE: 'TRANSACTION_DELETE',
};
