const authEnLang = {
  already_account: 'Already have an account?',
  new_user: 'New user?',
  forgot_password: 'Forgot password?',
  forgot_password_sub:
    'Please enter the email address associated with your account and We will email you a link to reset your password.',
  login: {
    label: 'Login',
    title: 'Login to',
  },
  register: {
    title: 'Get started absolutely free',
  },
  reset_password: {
    label: 'Reset password',
    title:
      'The link you clicked is invalid. Please request a new password reset.',
    description: 'Please enter your new password.',
  },
  verify_email: {
    label: 'Verify email',
    description: 'Please check your email inbox for the verification link.',
  },
  form: {
    fullname: 'Full name',
    email: 'Email',
    password: 'Password',
    register_button: 'Create Account',
    login_button: 'Login',
    fullname_required: 'Full name is required',
    email_required: 'Email is required',
    email_invalid: 'Email is invalid',
    password_required: 'Password is required',
    send_request: 'Send request',
    send_request_success:
      'We have sent you an email with a link to reset your password',
    return_to_login: 'Return to login',
    please_check_email: 'Please check your email!',
    check_email_inbox_code:
      'We have emailed a 6-digit confirmation code to {email}, please enter the code in below box to verify your email.',
    verify_code: 'Verify code',
    resend_code: 'Resend code',
    dont_have_code: 'Don’t have a code?',
    code_min: 'Code must be at least 6 characters',
    code_required: 'Code is required',
    token_required: 'Token is required',
    password_min: 'Password must be at least 6 characters',
    confirm_password_required: 'Confirm password is required',
    password_not_match: 'Password must match',
    reset_password_success: 'Reset password successfully',
    redirect_login: 'Redirect to login',
    confirm_password: 'Confirm password',
    back_to_login: 'Back to login',
    reset_password: 'Reset password',
    email_verified: 'Your account is already verified',
    resend_link: 'Resend link',
    logout: 'Logout',
  },
  error: {
    email_required: 'Email is required',
    password_required: 'Password is required',
    email_not_found: 'Email not found',
    user_not_found: 'User not found',
    refresh_token_required: 'Refresh token is required',
    user_not_found_with_refresh_token: 'User not found for this refresh token',
    refresh_token_invalid: 'Refresh token is invalid',
    please_wait_5_minutes: 'Please wait 5 minutes before trying again',
    token_required: 'Token is required',
    token_invalid: 'Token is invalid',
    token_expired: 'Token has expired',
    old_password_required: 'Old password is required',
    new_password_required: 'New password is required',
    password_is_incorrect: 'Password is incorrect',
    user_does_not_active: 'Account is not active',
    user_hold: 'Account is on hold',
    user_ban: 'Account is banned',
    user_deleted: 'Account has been deleted',
    fullname_required: 'Full name is required',
    user_is_verified: 'Account is already verified',
    id_required: 'ID is required',
    user_error: 'User error',
    email_already_exists: 'Email already exists',
    code_required: 'Verification code is required',
    code_invalid: 'Verification code is invalid',
    code_max_attempt: 'Maximum verification attempts reached',
  },
};
const authViLang = {
  already_account: 'Đã có tài khoản?',
  new_user: 'Người dùng mới?',
  forgot_password: 'Quên mật khẩu?',
  forgot_password_sub:
    'Vui lòng nhập địa chỉ email liên kết với tài khoản của bạn và chúng tôi sẽ gửi email cho bạn với liên kết để đặt lại mật khẩu.',
  login: {
    label: 'Đăng nhập',
    title: 'Đăng nhập vào',
  },
  register: {
    title: 'Bắt đầu hoàn toàn miễn phí',
  },
  reset_password: {
    label: 'Đặt lại mật khẩu',
    title:
      'Liên kết bạn đã nhấp vào không hợp lệ. Vui lòng yêu cầu đặt lại mật khẩu mới.',
    description: 'Vui lòng nhập mật khẩu mới của bạn.',
  },
  verify_email: {
    label: 'Xác minh email',
    description: 'Vui lòng kiểm tra hộp thư email của bạn để xác minh.',
  },
  form: {
    fullname: 'Họ và tên',
    email: 'Email',
    password: 'Mật khẩu',
    register_button: 'Tạo tài khoản',
    login_button: 'Đăng nhập',
    fullname_required: 'Họ và tên không được để trống',
    email_required: 'Email không được để trống',
    email_invalid: 'Email không hợp lệ',
    password_required: 'Mật khẩu không được để trống',
    send_request: 'Gửi yêu cầu',
    send_request_success:
      'Chúng tôi đã gửi email cho bạn với liên kết để đặt lại mật khẩu',
    return_to_login: 'Quay lại đăng nhập',
    please_check_email: 'Vui lòng kiểm tra email của bạn!',
    check_email_inbox_code:
      'Chúng tôi đã gửi một mã xác nhận 6 chữ số đến {email}, vui lòng nhập mã vào ô bên dưới để xác minh email của bạn.',
    verify_code: 'Xác minh mã',
    resend_code: 'Gửi lại mã',
    dont_have_code: 'Không nhận được mã?',
    code_min: 'Mã xác nhận phải có ít nhất 6 ký tự',
    code_required: 'Mã xác nhận không được để trống',
    token_required: 'Token không được để trống',
    password_min: 'Mật khẩu phải có ít nhất 6 ký tự',
    confirm_password_required: 'Xác nhận mật khẩu không được để trống',
    password_not_match: 'Mật khẩu phải khớp',
    reset_password_success: 'Đặt lại mật khẩu thành công',
    redirect_login: 'Chuyển hướng đến đăng nhập',
    confirm_password: 'Xác nhận mật khẩu',
    back_to_login: 'Quay lại đăng nhập',
    reset_password: 'Đặt lại mật khẩu',
    email_verified: 'Email đã được xác minh',
    resend_link: 'Gửi lại liên kết',
    logout: 'Đăng xuất',
  },
  error: {
    email_required: 'Email không được để trống',
    password_required: 'Mật khẩu không được để trống',
    email_not_found: 'Không tìm thấy email',
    user_not_found: 'Không tìm thấy người dùng',
    refresh_token_required: 'Refresh token không được để trống',
    user_not_found_with_refresh_token:
      'Không tìm thấy người dùng với refresh token này',
    refresh_token_invalid: 'Refresh token không hợp lệ',
    please_wait_5_minutes: 'Vui lòng đợi 5 phút trước khi thử lại',
    token_required: 'Token không được để trống',
    token_invalid: 'Token không hợp lệ',
    token_expired: 'Token đã hết hạn',
    old_password_required: 'Mật khẩu cũ không được để trống',
    new_password_required: 'Mật khẩu mới không được để trống',
    password_is_incorrect: 'Mật khẩu không đúng',
    user_does_not_active: 'Tài khoản chưa được kích hoạt',
    user_hold: 'Tài khoản đang tạm khóa',
    user_ban: 'Tài khoản đã bị cấm',
    user_deleted: 'Tài khoản đã bị xóa',
    fullname_required: 'Họ và tên không được để trống',
    user_is_verified: 'Tài khoản đã được xác minh',
    id_required: 'ID không được để trống',
    user_error: 'Lỗi người dùng',
    email_already_exists: 'Email đã tồn tại',
    code_required: 'Mã xác minh không được để trống',
    code_invalid: 'Mã xác minh không hợp lệ',
    code_max_attempt: 'Đã vượt quá số lần nhập mã xác minh',
  },
};

export { authEnLang, authViLang };
