const basicEnLang = {
  save: 'Save',
  cancel: 'Cancel',
  remove: 'Remove',
  edit: 'Edit',
  delete: 'Delete',
  deleted: 'Deleted',
  add: 'Add',
  create: 'Create',
  update: 'Update',
  back: 'Back',
  yes: 'Yes',
  no: 'No',
  search: 'Search',
  search_placeholder: 'Search...',
  clear: 'Clear',
  confirm: 'Confirm',
  seconds: 'seconds',
  minutes: 'minutes',
  hours: 'hours',
  days: 'days',
  noData: 'No data',
  copied: 'Copied',
  info: 'Info',
  upload: 'Upload',
  select: 'select',
  and: 'and',
  updatePhoto: 'Update photo',
  uploadPhoto: 'Upload photo',
  updateSuccess: 'Update successfully',
  updateFailed: 'Update failed',
  deleteSuccess: 'Delete successfully',
  createSuccess: 'Create successfully',
  cancelSuccess: 'Cancel successfully',
  viewDetails: 'View details',
  print: 'Print',
  export: 'Export',
  import: 'Import',
  reset: 'Reset',
  after: 'after',
  loadMore: 'Load more',
  all: 'All',
  filter: 'Filter',
  free: 'Free',
  verified: 'Verified',
  title: 'Title',
  content: 'Content',
  name: 'Name',
  createdAt: 'Created at',
  updatedAt: 'Updated at',
  status: 'Status',
  justNow: 'Just now',
  sortBy: 'Sort by',
  preview: 'Preview',
  emptyContent: 'Empty content',
  view: 'View',
  editLink: 'Edit link',
  unread: 'Unread',
  viewMore: 'View more',
  emptyData: 'Empty data',
  submitSuccess: 'Submit successfully',
  submitFailed: 'Submit failed',
  changeSuccess: 'Change successfully',
  phone: 'Phone',
  price: 'Price',
  user: 'User',
  reason: 'Reason',
  change: 'Change',
  type: 'Type',
  amount: 'Amount',
  doneAt: 'Done',
  description: 'Description',
  subtract: 'Subtract',
  endDate: 'End date',
  startDate: 'Start date',
  unknownUser: 'Unknown user',
  currency: '$',
  settings: 'Settings',
  mode: 'Mode',
  contrast: 'Contrast',
  direction: 'Direction',
  layout: 'Layout',
  stretch: 'Stretch',
  presets: 'Presets',
  exitFullscreen: 'Exit fullscreen',
  fullscreen: 'Fullscreen',
  generate: 'Generate',
  developmentEnvironment:
    'This is a demo page, only for testing purposes. The displayed data is not real data. Some features may be limited.',
  durations: {
    oneSecond: '1 second',
    seconds: '{count} seconds',
    oneMinute: '1 minute',
    minutes: '{count} minutes',
    oneHour: '1 hour',
    hours: '{count} hours',
    oneDay: '1 day',
    days: '{count} days',
    oneWeek: '1 week',
    weeks: '{count} weeks',
    oneMonth: '1 month',
    months: '{count} months',
    oneYear: '1 year',
    years: '{count} years',
  },
  active: 'Active',
  inactive: 'Inactive',
  not_enough_credit: 'Not enough credits',
  not_enough_commission: 'Not enough commission',
  admin: 'Admin',
  list: 'List',
  genders: {
    MALE: 'Male',
    FEMALE: 'Female',
    OTHER: 'Other',
  },
  profile: 'Profile',
  apply: 'Apply',
  sort: {
    latest: 'Latest',
    popular: 'Popular',
    oldest: 'Oldest',
    asc: 'Ascending',
    desc: 'Descending',
  },
  size: {
    none: 'None',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
  },
  min: 'Minimum',
  max: 'Maximum',
  receiveAmount: 'Receive amount',
  convert: 'Convert',
};

const basicViLang = {
  save: 'Lưu',
  remove: 'Xóa',
  cancel: 'Hủy',
  edit: 'Chỉnh sửa',
  delete: 'Xóa',
  deleted: 'Đã xóa',
  add: 'Thêm',
  create: 'Tạo mới',
  update: 'Cập nhật',
  back: 'Quay lại',
  yes: 'Có',
  no: 'Không',
  search: 'Tìm kiếm',
  search_placeholder: 'Tìm kiếm...',
  clear: 'Bỏ chọn',
  confirm: 'Xác nhận',
  seconds: 'giây',
  minutes: 'phút',
  hours: 'giờ',
  days: 'ngày',
  noData: 'Không có dữ liệu',
  copied: 'Đã sao chép',
  info: 'Thông tin',
  upload: 'Tải lên',
  select: 'chọn',
  and: 'và',
  updatePhoto: 'Cập nhật ảnh',
  uploadPhoto: 'Tải ảnh lên',
  updateSuccess: 'Cập nhật thành công',
  updateFailed: 'Cập nhật thất bại',
  deleteSuccess: 'Xóa thành công',
  createSuccess: 'Tạo mới thành công',
  cancelSuccess: 'Hủy thành công',
  viewDetails: 'Xem chi tiết',
  print: 'In',
  export: 'Xuất',
  import: 'Nhập',
  reset: 'Đặt lại',
  after: 'sau',
  loadMore: 'Tải thêm',
  all: 'Tất cả',
  filter: 'Lọc',
  free: 'Miễn phí',
  verified: 'Đã xác minh',
  title: 'Tiêu đề',
  content: 'Nội dung',
  name: 'Tên',
  createdAt: 'Ngày tạo',
  updatedAt: 'Ngày cập nhật',
  status: 'Trạng thái',
  justNow: 'Vừa xong',
  sortBy: 'Sắp xếp theo',
  preview: 'Xem trước',
  emptyContent: 'Nội dung trống',
  view: 'Xem',
  editLink: 'Chỉnh sửa liên kết',
  unread: 'Chưa đọc',
  viewMore: 'Xem thêm',
  emptyData: 'Dữ liệu trống',
  submitSuccess: 'Gửi thành công',
  submitFailed: 'Gửi thất bại',
  changeSuccess: 'Thay đổi thành công',
  phone: 'Số điện thoại',
  price: 'Giá',
  user: 'Người dùng',
  reason: 'Lý do',
  change: 'Thay đổi',
  type: 'Loại',
  amount: 'Số lượng',
  doneAt: 'Hoàn thành',
  description: 'Mô tả',
  subtract: 'Trừ',
  startDate: 'Ngày bắt đầu',
  endDate: 'Ngày kết thúc',
  unknownUser: 'Người dùng không xác định',
  currency: '₫',
  settings: 'Cài đặt',
  mode: 'Chế độ',
  contrast: 'Contrast',
  direction: 'Hướng',
  layout: 'Bố cục',
  stretch: 'Kéo giãn',
  presets: 'Presets',
  exitFullscreen: 'Thoát khỏi toàn màn hình',
  fullscreen: 'Toàn màn hình',
  generate: 'Tạo',
  developmentEnvironment:
    'Đây là trang demo, chỉ dành cho mục đích thử nghiệm. Dữ liệu hiển thị không phải dữ liệu thật. Một số tính năng có thể bị giới hạn.',
  durations: {
    oneSecond: '1 giây',
    seconds: '{count} giây',
    oneMinute: '1 phút',
    minutes: '{count} phút',
    oneHour: '1 giờ',
    hours: '{count} giờ',
    oneDay: '1 ngày',
    days: '{count} ngày',
    oneWeek: '1 tuần',
    weeks: '{count} tuần',
    oneMonth: '1 tháng',
    months: '{count} tháng',
    oneYear: '1 năm',
    years: '{count} năm',
  },
  active: 'Hoạt động',
  inactive: 'Không hoạt động',
  not_enough_credit: 'Không đủ credits',
  not_enough_commission: 'Không đủ hoa hồng',
  admin: 'Quản trị viên',
  list: 'Danh sách',
  genders: {
    MALE: 'Nam',
    FEMALE: 'Nữ',
    OTHER: 'Khác',
  },
  profile: 'Hồ sơ',
  apply: 'Áp dụng',
  sort: {
    latest: 'Mới nhất',
    popular: 'Phổ biến',
    oldest: 'Cũ nhất',
    asc: 'Tăng dần',
    desc: 'Giảm dần',
  },
  size: {
    none: 'Ẩn',
    small: 'Nhỏ',
    medium: 'Vừa',
    large: 'Lớn',
  },
  min: 'Tối thiểu',
  max: 'Tối đa',
  receiveAmount: 'Số lượng nhận',
  convert: 'Quy đổi',
};

export { basicEnLang, basicViLang };
