const formEnLang = {
  warningFormDialogTitle: 'The data you just entered has not been saved',
  warningFormDialogContent: 'Are you sure you want to leave this page?',
  name: 'Name',
  username: 'Username',
  email: 'Email',
  phone: 'Phone',
  address: 'Address',
  country: 'Country',
  region: 'Region',
  city: 'City',
  zip_code: 'Zip code',
  newPassword: 'New password',
  oldPassword: 'Old password',
  confirmNewPassword: 'Confirm new password',
  passwordHelper: 'Password must be at least 6 characters',
  title: 'Title',
  role: 'Role',
  password: 'Password',
  status: 'Status',
  level: 'Level',
  referrer: 'Referrer',
  content: 'Content',
  credits: 'Credits',
  gender: 'Gender',
};
const formViLang = {
  warningFormDialogTitle: 'Dữ liệu bạn vừa nhập chưa được lưu',
  warningFormDialogContent: 'Bạn có chắc chắn muốn rời khỏi trang này không ?',
  name: 'Tên',
  username: 'Tên đăng nhập',
  email: 'Email',
  phone: 'Số điện thoại',
  address: 'Địa chỉ',
  country: 'Quốc gia',
  region: 'Quận/Huyện',
  city: 'Tỉnh/Thành phố',
  zip_code: 'Mã bưu điện',
  newPassword: 'Mật khẩu mới',
  oldPassword: 'Mật khẩu cũ',
  confirmNewPassword: 'Xác nhận mật khẩu mới',
  passwordHelper: 'Mật khẩu phải có ít nhất 6 ký tự',
  title: 'Tiêu đề',
  role: 'Vai trò',
  password: 'Mật khẩu',
  status: 'Trạng thái',
  level: 'Cấp độ',
  referrer: 'Người giới thiệu',
  content: 'Nội dung',
  credits: 'Credits',
  gender: 'Giới tính',
};

export { formEnLang, formViLang };
