const paymentsEnLang = {
  label: 'Payments',
  new: 'New payment',
  title: 'Top up credits to your account',
  subtitle: 'Choose the package that suits your needs',
  package: 'Package',
  method: 'Payment method',
  summary: 'Summary',
  paymentPrice: 'Payment amount',
  totalBilled: 'Total billed',
  checkout: 'Checkout',
  invalidPackage: 'Invalid package',
  orderCode: 'Payment code',
  customer: 'Customer',
  orderId: 'Order ID',
  bankCode: 'Bank code',
  createPayment: 'Create payment',
  approve: 'Approve',
  approveSuccess: 'Approve payment successfully',
  approveFailed: 'Approve payment failed',
  approveConfirm: 'Are you sure to approve this payment?',
  approveConfirmMessage: 'This action cannot be undone',
  reject: 'Reject',
  rejectSuccess: 'Reject payment successfully',
  rejectFailed: 'Reject payment failed',
  rejectConfirm: 'Are you sure to reject this payment?',
  rejectConfirmMessage: 'This action cannot be undone',
  reopen: 'Reopen',
  reopenSuccess: 'Reopen payment successfully',
  reopenFailed: 'Reopen payment failed',
  reopenConfirm: 'Are you sure to reopen this payment?',
  reopenConfirmMessage: 'This action cannot be undone',
  notFound: 'Payment not found',
  transactions: 'Transactions',
  orders: 'Orders',
  error: {
    not_found: 'Payment not found',
    not_pending: 'Payment is not pending',
    unique_id_error: 'Payment ID already exists',
    invalid_package: 'Invalid package',
    action_invalid: 'Invalid action',
    action_payload_too_large: 'Action payload is too large',
    guest_user_resolve_failed: 'Could not resolve guest user',
    guest_rate_limited: 'Too many requests. Please try again later',
    bank_code_required: 'Bank code is required',
    can_not_reopen_when_already_dispatched:
      'Cannot reopen payment that has already been dispatched',
  },
  methods: {
    MOMO: 'Momo',
    BANK_TRANSFER: 'Bank transfer',
  },
  status: {
    PENDING: 'Waiting for payment',
    PROCESSING: 'Processing',
    COMPLETED: 'Paid',
    CANCELED: 'Canceled',
  },
  depositCredits: 'Deposit credits',
  transactionHistory: 'Transaction history',
  convertCommission: 'Convert commission',
  convertCommissionInfo: 'Convert commission to credits',
  convertCommissionSuccess: 'Convert commission successfully',
  convertCommissionFailed: 'Convert commission failed',
};
const paymentsViLang = {
  label: 'Thanh toán',
  new: 'Thanh toán mới',
  title: 'Nạp credits vào tài khoản',
  subtitle: 'Hãy chọn gói phù hợp với nhu cầu của bạn',
  package: 'Gói',
  method: 'Phương thức thanh toán',
  summary: 'Xem lại đơn hàng',
  paymentPrice: 'Số tiền thanh toán',
  totalBilled: 'Tổng cộng',
  checkout: 'Thanh toán',
  invalidPackage: 'Gói không hợp lệ',
  orderCode: 'Mã đơn hàng',
  customer: 'Khách hàng',
  orderId: 'Mã đơn hàng',
  bankCode: 'Mã ngân hàng',
  createPayment: 'Tạo thanh toán',
  approve: 'Duyệt',
  approveSuccess: 'Duyệt thanh toán thành công',
  approveFailed: 'Duyệt thanh toán thất bại',
  approveConfirm: 'Bạn có chắc chắn muốn duyệt thanh toán này?',
  approveConfirmMessage: 'Hành động này không thể hoàn tác',
  reject: 'Từ chối',
  rejectSuccess: 'Từ chối thanh toán thành công',
  rejectFailed: 'Từ chối thanh toán thất bại',
  rejectConfirm: 'Bạn có chắc chắn muốn từ chối thanh toán này?',
  rejectConfirmMessage: 'Hành động này không thể hoàn tác',
  reopen: 'Mở lại',
  reopenSuccess: 'Mở lại thanh toán thành công',
  reopenFailed: 'Mở lại thanh toán thất bại',
  reopenConfirm: 'Bạn có chắc chắn muốn mở lại thanh toán này?',
  reopenConfirmMessage: 'Hành động này không thể hoàn tác',
  notFound: 'Không tìm thấy thanh toán',
  transactions: 'Giao dịch',
  orders: 'Đơn hàng',
  error: {
    not_found: 'Không tìm thấy thanh toán',
    not_pending: 'Thanh toán không ở trạng thái chờ xử lý',
    unique_id_error: 'Mã thanh toán đã tồn tại',
    invalid_package: 'Gói không hợp lệ',
    action_invalid: 'Hành động không hợp lệ',
    action_payload_too_large: 'Dữ liệu hành động quá lớn',
    guest_user_resolve_failed: 'Không thể xác định người dùng khách',
    guest_rate_limited: 'Quá nhiều yêu cầu. Vui lòng thử lại sau',
    bank_code_required: 'Mã ngân hàng không được để trống',
    can_not_reopen_when_already_dispatched:
      'Không thể mở lại thanh toán đã được xử lý',
  },
  methods: {
    MOMO: 'Momo',
    BANK_TRANSFER: 'Chuyển khoản ngân hàng',
  },
  status: {
    PENDING: 'Chờ thanh toán',
    PROCESSING: 'Đang xử lý',
    COMPLETED: 'Đã thanh toán',
    CANCELED: 'Đã hủy',
  },
  depositCredits: 'Nạp credits',
  transactionHistory: 'Lịch sử giao dịch',
  convertCommission: 'Quy đổi commission',
  convertCommissionInfo: 'Quy đổi commission thành credits',
  convertCommissionSuccess: 'Quy đổi commission thành công',
  convertCommissionFailed: 'Quy đổi commission thất bại',
};

export { paymentsEnLang, paymentsViLang };
