const postsEnLang = {
  list: 'List',
  new: 'New',
  edit: 'Edit',
  create: 'Create new post',
  details: 'Details',
  detailsDescription: 'Title, short description, image...',
  properties: 'Properties',
  propertiesDescription: 'Additional functions and attributes...',
  title: 'Title',
  description: 'Description',
  content: 'Content',
  image: 'Image',
  tags: 'Tags',
  metaTitle: 'Meta title',
  metaDescription: 'Meta description',
  metaKeywords: 'Meta keywords',
  keywords: 'Keywords',
  metaImage: 'Meta image',
  enableComments: 'Enable comments',
  isShowMain: 'Show on main page',
  publishDate: 'Publish date',
  hot: 'Featured',
  notFound: 'Posts not found',
  bounty: 'Bounty',
  bountyHistory: 'Bounty history',
  bountySuccess: 'Bounty successful',
  bountyFailed: 'Bounty failed',
  status: {
    DRAFT: 'Draft',
    PENDING: 'Pending',
    PUBLISHED: 'Published',
    SCHEDULED: 'Scheduled',
    TRASH: 'Trash',
  },
  goLive: 'Go live',
  error: {
    not_found: 'Posts not found',
    title_required: 'Title is required',
    does_not_allowed: 'Does not allowed',
    cant_view_draft: 'Can not view draft',
  },
  newPost: 'New post',
};
const postsViLang = {
  list: 'Danh sách',
  new: 'Tạo mới',
  edit: 'Chỉnh sửa',
  create: 'Tạo bài viết',
  details: 'Chi tiết',
  detailsDescription: 'Tiêu đề, mô tả ngắn, hình ảnh...',
  properties: 'Thuộc tính',
  propertiesDescription: 'Các chức năng và thuộc tính khác...',
  title: 'Tiêu đề',
  description: 'Mô tả',
  content: 'Nội dung',
  image: 'Hình ảnh',
  tags: 'Tags',
  metaTitle: 'Meta title',
  metaDescription: 'Meta description',
  metaKeywords: 'Meta keywords',
  keywords: 'Keywords',
  metaImage: 'Meta image',
  enableComments: 'Bật bình luận',
  isShowMain: 'Hiển thị trên trang chính',
  publishDate: 'Ngày xuất bản',
  hot: 'Nổi bật',
  notFound: 'Không tìm thấy bài viết',
  bounty: 'Thưởng',
  bountyHistory: 'Lịch sử thưởng',
  bountySuccess: 'Thưởng thành công',
  bountyFailed: 'Thưởng thất bại',
  status: {
    DRAFT: 'Nháp',
    PENDING: 'Chờ duyệt',
    PUBLISHED: 'Đã xuất bản',
    SCHEDULED: 'Đã lên lịch',
    TRASH: 'Thùng rác',
  },
  goLive: 'Xem trực tiếp',
  error: {
    not_found: 'Bài viết không tồn tại',
    title_required: 'Tiêu đề là bắt buộc',
    does_not_allowed: 'Không được phép',
    cant_view_draft: 'Không thể xem nháp',
  },
  newPost: 'Bài viết mới',
};

export { postsEnLang, postsViLang };
