const usersEnLang = {
  editProfile: 'Edit Profile',
  about: 'About',
  liveAt: 'Live at',
  general: 'General',
  billing: 'Billing',
  transactions: 'Transactions',
  orders: 'Orders',
  social: 'Social',
  notifications: 'Notifications',
  security: 'Security',
  account: 'Account',
  notificationSettings: {
    caption: 'Choose how you want to be notified for each event',
    email: 'Email',
    inApp: 'In-app',
    types: {
      like: 'Likes on your content',
      comment: 'Comments on your content',
      payment: 'Payment updates',
    },
  },
  publicProfile: 'Public Profile',
  publicEmail: 'Public Email',
  publicPhone: 'Public Phone',
  changePassword: 'Change Password',
  newUser: 'New User',
  editUser: 'Edit User',
  verified: 'Verified',
  quickEdit: 'Quick Edit',
  name: 'Name',
  status: 'Status',
  role: 'Role',
  level: 'Level',
  referrer: 'Ref',
  createdAt: 'Created At',
  list: 'List',
  filter: 'Filter',
  statuses: {
    all: 'All',
    ALL: 'All',
    PENDING: 'Pending',
    ACTIVE: 'Active',
    HOLD: 'Hold',
    BAN: 'Ban',
    DELETE: 'Delete',
  },
  error: {
    user_not_found: 'User not found',
    not_found: 'User not found',
    email_required: 'Email is required',
    email_exists: 'Email already exists',
    fullname_required: 'Full name is required',
    does_not_allowed: 'Action not allowed',
    username_exists: 'Username already exists',
    phone_exists: 'Phone number already exists',
    cannot_delete_ai_user: 'Cannot delete AI user',
    cannot_follow_yourself: 'You cannot follow yourself',
    user_not_public: 'User profile is not public',
    media_not_found: 'Media not found',
    media_exists: 'Media already exists',
    invalid_coach_review_price: 'Invalid coach review price',
  },
};

const usersViLang = {
  editProfile: 'Chỉnh sửa hồ sơ',
  about: 'Thông tin',
  liveAt: 'Địa chỉ',
  general: 'Chung',
  billing: 'Thanh toán',
  transactions: 'Giao dịch',
  orders: 'Đơn hàng',
  social: 'Mạng xã hội',
  notifications: 'Thông báo',
  security: 'Bảo mật',
  account: 'Tài khoản',
  notificationSettings: {
    caption: 'Chọn cách bạn muốn nhận thông báo cho từng sự kiện',
    email: 'Email',
    inApp: 'Trong ứng dụng',
    types: {
      like: 'Lượt thích trên nội dung của bạn',
      comment: 'Bình luận trên nội dung của bạn',
      payment: 'Cập nhật thanh toán',
    },
  },
  publicProfile: 'Hiển thị hồ sơ',
  publicEmail: 'Hiển thị email',
  publicPhone: 'Hiển thị số điện thoại',
  changePassword: 'Đổi mật khẩu',
  newUser: 'Người dùng mới',
  editUser: 'Chỉnh sửa người dùng',
  verified: 'Đã xác minh',
  quickEdit: 'Chỉnh sửa nhanh',
  name: 'Tên',
  status: 'Trạng thái',
  role: 'Vai trò',
  level: 'Cấp độ',
  referrer: 'Ref',
  createdAt: 'Ngày tạo',
  list: 'Danh sách',
  filter: 'Lọc',
  statuses: {
    all: 'Tất cả',
    ALL: 'Tất cả',
    PENDING: 'Chờ duyệt',
    ACTIVE: 'Hoạt động',
    HOLD: 'Tạm khóa',
    BAN: 'Cấm',
    DELETE: 'Xóa',
  },
  error: {
    user_not_found: 'Không tìm thấy người dùng',
    not_found: 'Không tìm thấy người dùng',
    email_required: 'Email không được để trống',
    email_exists: 'Email đã tồn tại',
    fullname_required: 'Họ và tên không được để trống',
    does_not_allowed: 'Không được phép thực hiện',
    username_exists: 'Tên đăng nhập đã tồn tại',
    phone_exists: 'Số điện thoại đã tồn tại',
    cannot_delete_ai_user: 'Không thể xóa người dùng AI',
    cannot_follow_yourself: 'Bạn không thể theo dõi chính mình',
    user_not_public: 'Hồ sơ người dùng không công khai',
    media_not_found: 'Không tìm thấy media',
    media_exists: 'Media đã tồn tại',
    invalid_coach_review_price: 'Giá đánh giá coach không hợp lệ',
  },
};

export { usersEnLang, usersViLang };
