const validateEnLang = {
  required: 'Required',
  nameRequired: 'Name is required',
  usernameRequired: 'Username is required',
  emailRequired: 'Email is required',
  emailInvalid: 'Email is invalid',
  phoneRequired: 'Phone is required',
  addressRequired: 'Address is required',
  countryRequired: 'Country is required',
  regionRequired: 'Region is required',
  cityRequired: 'City is required',
  zipCodeRequired: 'Zip code is required',
  aboutRequired: 'About is required',
  urlInvalid: 'URL is invalid',
  oldPasswordRequired: 'Old password is required',
  newPasswordRequired: 'New password is required',
  newPasswordMin: 'New password must be at least 6 characters',
  newPasswordMatch: 'New password must not match',
  confirmPasswordMatch: 'Confirm password must match',
  titleRequired: 'Title is required',
  descriptionRequired: 'Description is required',
  contentRequired: 'Content is required',
  maxLength: 'Max length {length}',
};
const validateViLang = {
  required: 'Bắt buộc',
  nameRequired: 'Tên không được để trống',
  usernameRequired: 'Tên đăng nhập không được để trống',
  emailRequired: 'Email không được để trống',
  emailInvalid: 'Email không hợp lệ',
  phoneRequired: 'Số điện thoại không được để trống',
  addressRequired: 'Địa chỉ không được để trống',
  countryRequired: 'Quốc gia không được để trống',
  regionRequired: 'Khu vực không được để trống',
  cityRequired: 'Thành phố không được để trống',
  zipCodeRequired: 'Mã bưu điện không được để trống',
  aboutRequired: 'Thông tin không được để trống',
  urlInvalid: 'URL không hợp lệ',
  oldPasswordRequired: 'Mật khẩu cũ không được để trống',
  newPasswordRequired: 'Mật khẩu mới không được để trống',
  newPasswordMin: 'Mật khẩu mới phải có ít nhất 6 ký tự',
  newPasswordMatch: 'Mật khẩu mới không đươc trùng với mật khẩu cũ',
  confirmPasswordMatch: 'Xác nhận mật khẩu không khớp',
  titleRequired: 'Tiêu đề không được để trống',
  descriptionRequired: 'Mô tả không được để trống',
  contentRequired: 'Nội dung không được để trống',
  maxLength: 'Tối đa {length} ký tự',
};

export { validateEnLang, validateViLang };
