export const userMetaKey = {
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  PASSWORD_RESET_TOKEN: 'PASSWORD_RESET_TOKEN',
  SETTING: 'SETTING',
  CONFIRM_REGISTER_TOKEN: 'CONFIRM_REGISTER_TOKEN',
  CONFIRM_REGISTER_CODE: 'CONFIRM_REGISTER_CODE',
  CONFIRM_REGISTER_CODE_COUNT: 'CONFIRM_REGISTER_CODE_COUNT',
};
