import { Prisma } from '@prisma/client';

export const getMeSelect: Prisma.UserSelect = {
  id: true,
  email: true,
  about: true,
  username: true,
  fullname: true,
  phone: true,
  socials: true,
  address: true,
  country: true,
  city: true,
  region: true,
  zipCode: true,
  avatarId: true,
  avatar: true,
  cover: true,
  coverId: true,
  status: true,
  deleted: true,
  isVerified: true,
  referrerId: true,
  referrer: true,
  score: true,
  credits: true,
  commissions: true,
  level: true,
  activityStatus: true,
  lastActivity: true,
  gender: true,
  createdAt: true,
  updatedAt: true,
  role: {
    select: {
      id: true,
      name: true,
      permissions: true,
      createdAt: true,
      updatedAt: true,
    },
  },
  setting: true,
};
