import Iconify from '../components/iconify';
import Image from '../components/image';
import SvgColor from '../components/svg-color';

const icon = (name: string, type: 'svg' | 'icon' | 'image' = 'svg') => {
  // https://icon-sets.iconify.design/solar/
  // https://www.streamlinehq.com/icons
  if (type === 'icon') return <Iconify icon={name} />;
  if (type === 'image')
    return <Image width={24} height={24} src={name} alt={name} />;
  return (
    <SvgColor
      src={`/assets/icons/navbar/${name}.svg`}
      sx={{ width: 1, height: 1 }}
    />
  );
};
export const ICONS = {
  fitnessBase: icon('/images/favicon.png', 'image'),
  job: icon('ic_job'),
  blog: icon('ic_blog'),
  chat: icon('ic_chat'),
  mail: icon('ic_mail'),
  user: icon('ic_user'),
  file: icon('ic_file'),
  lock: icon('ic_lock'),
  tour: icon('ic_tour'),
  order: icon('ic_order'),
  label: icon('ic_label'),
  blank: icon('ic_blank'),
  kanban: icon('ic_kanban'),
  folder: icon('ic_folder'),
  banking: icon('ic_banking'),
  booking: icon('ic_booking'),
  invoice: icon('ic_invoice'),
  product: icon('ic_product'),
  calendar: icon('ic_calendar'),
  disabled: icon('ic_disabled'),
  external: icon('ic_external'),
  menuItem: icon('ic_menu_item'),
  ecommerce: icon('ic_ecommerce'),
  analytics: icon('ic_analytics'),
  dashboard: icon('ic_dashboard'),
  knowledge: icon('ic_knowledge'),
  member: icon('clarity:group-solid', 'icon'),
  emailTemplate: icon('lsicon:email-send-outline', 'icon'),
  specialization: icon('mdi:certificate', 'icon'),
  payment: icon('ic:twotone-payment', 'icon'),
  rewards: icon('ic_invoice'),
  bugReport: icon('solar:bug-bold-duotone', 'icon'),
  coachRequest: icon('icon-park-outline:add-two', 'icon'),
  settings: icon('solar:settings-bold-duotone', 'icon'),
  badge: icon('material-symbols-light:crown', 'icon'),
  challenge: icon('solar:cup-star-bold-duotone', 'icon'),
  feed: icon('material-symbols:rss-feed-rounded', 'icon'),
  wallet: icon('solar:wallet-bold-duotone', 'icon'),
};

export const ICONS_NAME = {
  edit: 'solar:pen-bold',
  editDetail: 'lucide:edit',
  search: 'eva:search-fill',
  loading: 'svg-spinners:8-dots-rotate',
  verified: 'ic:round-verified',
  specialization: 'mdi:certificate',
  security: 'ic:round-vpn-key',
  social: 'solar:share-bold',
  privacy: 'material-symbols:lock',
  notifications: 'solar:bell-bing-bold',
  billing: 'solar:bill-list-bold',
  general: 'solar:user-id-bold',
  delete: 'solar:trash-bin-trash-bold',
  linkExternal: 'formkit:linkexternal',
  more: 'eva:more-vertical-fill',
  view: 'eva:eye-outline',
  info: 'eva:info-outline',
  infoFill: 'material-symbols:info',
  copy: 'solar:copy-outline',
  credit: 'game-icons:crown-coin',
  plus: 'ic:baseline-plus',
  history: 'material-symbols:history',
  close: 'material-symbols:close',
  tip: 'ic:baseline-tips-and-updates',
  theme: 'line-md:light-dark',
  settings: 'solar:settings-bold-duotone',
  dark: 'solar:moon-bold',
  light: 'solar:sun-bold',
  referral: 'ri:user-star-line',
  check: 'material-symbols:check',
  checked: 'icon-park-twotone:check-one',
  unchecked: 'icon-park-twotone:close-one',
  rewards: 'solar:gift-bold',
  partner: 'mdi:partnership-outline',
  actionList: 'material-symbols:action-key',
  minusCircle: 'zondicons:minus-outline',
  addCircle: 'zondicons:add-outline',
  strength: 'mingcute:fitness-fill',
  clock: 'mdi:account-clock',
  warning: 'material-symbols:warning',
  warningColor: 'fluent-color:warning-16',
  infoColor: 'flat-color-icons:info',
  send: 'material-symbols:send',
  galleryAdd: 'solar:gallery-add-bold',
  reply: 'solar:reply-bold',
  markAllAsRead: 'eva:done-all-fill',
  emoji: 'eva:smiling-face-fill',
  save: 'material-symbols:save',
  drag: 'mdi:drag-vertical',
  add: 'material-symbols:add',
  pause: 'mdi:pause',
  play: 'mdi:play',
  volume: 'mdi:volume-high',
  volumeOff: 'mdi:volume-off',
  fullscreen: 'mdi:fullscreen',
  fullscreenExit: 'mdi:fullscreen-exit',
  completed: 'fluent-mdl2:completed-solid',
  enroll: 'mdi:users',
  progress: 'svg-spinners:clock',
  generate: 'oui:generate',
  quiz: 'mingcute:question-fill',
  trophy: 'noto:trophy',
  list: 'material-symbols:list',
  payment: 'streamline-color:payment-10',
  errorFill: 'fluent-mdl2:status-error-full',
  challenge: 'solar:cup-star-bold-duotone',
  information: 'solar:file-text-bold-duotone',
  teams: 'solar:users-group-two-rounded-bold-duotone',
  timeline: 'mdi:timeline-check',
  step: 'flat-color-icons:timeline',
  target: 'mdi:target',
  time: 'mdi:timer-outline',
  chevronRight: 'eva:arrow-ios-forward-fill',
  chevronLeft: 'eva:arrow-ios-back-fill',
  chevronUp: 'eva:arrow-ios-upward-fill',
  chevronDown: 'eva:arrow-ios-downward-fill',
  arrowRight: 'material-symbols:arrow-forward-rounded',
  arrowLeft: 'material-symbols:arrow-back-rounded',
  arrowUp: 'material-symbols:arrow-upward-rounded',
  arrowDown: 'material-symbols:arrow-downward-rounded',
  reload: 'material-symbols:refresh',
  commission: 'mdi:hand-coin',
  message: 'ic:baseline-message',
  affiliate: 'icon-park-outline:connect',
  click: 'material-symbols:ads-click',
  login: 'material-symbols:login',
  convert: 'material-symbols:change-circle-outline',
  wallet: 'solar:wallet-bold-duotone',
  approximatelySign: 'mdi:approximately-equal',
};
