export const queryName = {
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_PAYMENTS: 'GET_PAYMENTS',
  GET_PAYMENT: 'GET_PAYMENT',
  GET_PAYMENT_SUMMARY: 'GET_PAYMENT_SUMMARY',
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  GET_USERS_COUNT: 'GET_USERS_COUNT',
  GET_NOTIFICATION_SYSTEM: 'GET_NOTIFICATION_SYSTEM',

  // Post
  GET_POST_LIST_HOME: 'GET_POST_LIST_HOME',
  GET_POST_LIST: 'GET_POST_LIST',
  GET_POST_BY_SLUG: 'GET_POST_BY_SLUG',
  GET_POST_SUMMARY: 'GET_POST_SUMMARY',
  GET_POST_BOUNTY: 'GET_POST_BOUNTY',

  // Email Template
  GET_EMAIL_TEMPLATE_BY_KEY: 'GET_EMAIL_TEMPLATE_BY_KEY',

  // Websocket
  GET_ONLINE_USERS: 'GET_ONLINE_USERS',

  // Transaction
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  GET_TRANSACTION: 'GET_TRANSACTION',
};
